globals:
  SystemJS: true
  __moduleName: true
plugins:
  - vue
extends:
  - plugin:vue/essential
  - eslint:recommended
  - google
  - plugin:vue/recommended
  - prettier
  - prettier/vue
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  eol-last:
    - 0
  indent: 0
  no-else-return: 1
  max-len: [error, 120]
  new-cap: 0
  no-console: 0
  no-new: warn
  no-var: error
  no-unused-vars: error
  require-jsdoc: off
  valid-jsdoc: off
  prefer-const: error
  vue/name-property-casing: ['error', 'kebab-case']
  vue/require-default-prop: 'off'
  vue/no-v-model-argument: 'off'
env:
  browser: true
  commonjs: true
  node: true
  es6: true
  jest: true
  jasmine: true
